import unittest
from selenium import webdriver
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

class TestRank(unittest.TestCase):
    def setUp(self):
        options = webdriver.ChromeOptions()
        options.add_experimental_option('excludeSwitches', ['enable-logging'])
        self.driver = webdriver.Chrome(options=options)
        self.driver.get("http://localhost:3000/")
        time.sleep(1)

    def test_rank(self):
        # Find the search box element and enter the search term
        self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/main[2]/div/div[2]/div/div[2]/button').click()
        time.sleep(1)
        mail = self.driver.find_element(By.XPATH, '/html/body/div/div[1]/div/main/div/form/div[1]/div/input')
        mail.send_keys("admin@spr1.com")
        time.sleep(1)
        passw = self.driver.find_element(By.XPATH, '/html/body/div/div[1]/div/main/div/form/div[2]/div/input')
        passw.send_keys("12345678")
        self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/main/div/form/button').click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/header/div/div/div[3]/button[5]').click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/center/div[1]/button').click()
        time.sleep(5)
        firstref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[1]/div[3]/div') 
        secondref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[2]/div[3]/div') 
        thirdref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[3]/div[3]/div') 
        fourthref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[4]/div[3]/div') 
        fifthref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[5]/div[3]/div') 
        sixthref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[6]/div[3]/div') 
        seventhref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[7]/div[3]/div') 
        eigthref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[8]/div[3]/div') 
        ninthref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[9]/div[3]/div') 
        self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        self.assertTrue(firstref and secondref and thirdref and fourthref and fifthref and sixthref and seventhref and eigthref and ninthref, "Referee data is not proper on ranking list!")
        print("1/3 Referee table is accurate, first test has passed. ✅")
        bestref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/div/div[2]/center/h3') 
        self.assertTrue(bestref.text == firstref.text, "Best performance is wrong!")
        print("2/3 Best performance is accurate, second test has passed. ✅")
        matchname = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/div/div[2]/center/h6')
        tablematch = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[1]/div[6]/div')
        self.assertTrue(matchname.text == tablematch.text, "Best performance is wrong!")
        print("3/3 Match names are accurate, third test has passed. ✅")
        time.sleep(2)
        self.driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(1)
        self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/header/div/div/div[3]/button[5]').click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/center/div[1]/nav/ul/li[5]/button').click()
        time.sleep(2)
        print("Second round has started!")
        self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/center/div[1]/button').click()
        time.sleep(5)
        firstref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[1]/div[3]/div') 
        secondref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[2]/div[3]/div') 
        thirdref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[3]/div[3]/div') 
        fourthref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[4]/div[3]/div') 
        fifthref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[5]/div[3]/div') 
        sixthref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[6]/div[3]/div') 
        seventhref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[7]/div[3]/div') 
        eigthref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[8]/div[3]/div') 
        ninthref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[9]/div[3]/div') 
        self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        self.assertTrue(firstref and secondref and thirdref and fourthref and fifthref and sixthref and seventhref and eigthref and ninthref, "Referee data is not proper on ranking list!")
        print("1/3 Referee table is accurate, first test has passed. ✅")
        bestref = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/div/div[2]/center/h3') 
        self.assertTrue(bestref.text == firstref.text, "Best performance is wrong!")
        print("2/3 Best performance is accurate, second test has passed. ✅")
        matchname = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/div/div[2]/center/h6')
        tablematch = self.driver.find_element(By.XPATH, '//*[@id="root"]/div[1]/div/div/div/center/div[2]/div/div[2]/div[2]/div/div/div/div[1]/div[6]/div')
        self.assertTrue(matchname.text == tablematch.text, "Best performance is wrong!")
        print("3/3 Match names are accurate, third test has passed. ✅")
        time.sleep(2)
        self.driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(1)
        print("All tests are completed! ✅")
        self.driver.close()

 